class SlotGameV3 {
 constructor(){this.setting=1;this.state=GAME_STATE.NORMAL;this.currentG=0;this.artG=0;this.credit=0;this.artStock=0;this.bet=0;this.currentRole=null;this.hintRole=null;this.payment=0;this.spinInProgress=false;this.bonusPending=false;this.bonusCountdown=0;this.bonusType=null;this.bonusPayout=0;this.bonusRemaining=0;this.bonusGameG=0;this.fakePrecursorG=0;this.challengeG=0;this.challengeSmall=false;this.challengeSuccess=false;this.hasBonus=false;}
 setSetting(s){if(s<1||s>6)return;this.setting=s;storage.setSetting(s);}
 placeBet(){if(this.state!==GAME_STATE.NORMAL||this.bet>0||this.credit<BET_AMOUNT)return false;if(!storage.removeCredit(BET_AMOUNT))return false;this.credit-=BET_AMOUNT;this.bet=BET_AMOUNT;this.payment=0;return true;}
 draw(roles){let r=Math.random(),c=0;const a=Object.values(roles);for(const x of a){c+=x.prob;if(r<c)return x;}return roles.LOSE||roles.ART_LOSE||a[a.length-1];}
 rollNormal(){if(this.state!==GAME_STATE.NORMAL||this.bet<=0||this.spinInProgress)return false;this.currentRole=this.draw(NORMAL_ROLES);this.hintRole=this.currentRole;this.payment=this.currentRole.payment||0;this.spinInProgress=true;if(!this.bonusPending)this.checkBonus();return true;}
 checkBonus(){const r=BONUS_TRIGGER_RATES[this.setting],n=this.currentRole.name;let p=0;if(n.includes('チャンス目'))p=r.CHANCE;else if(n.includes('強チェリー'))p=r.STRONG_CHERRY;else if(n.includes('スイカ'))p=r.WATERMELON;else if(n.includes('弱チェリー'))p=r.WEAK_CHERRY;else if(this.currentRole.isLose)p=r.LOSE;if(Math.random()<p){this.bonusPending=true;this.bonusType=Math.random()<BONUS_BIG_RATIO?'BIG':'REG';this.bonusCountdown=2+Math.floor(Math.random()*4);this.fakePrecursorG=0;}else{let f=.045;if(n.includes('強チェリー')||n.includes('チャンス目'))f=.34;else if(n.includes('スイカ')||n.includes('弱チェリー'))f=.16;if(Math.random()<f)this.fakePrecursorG=2+Math.floor(Math.random()*3);}}
 advancePresentation(){if(this.bonusPending){this.bonusCountdown--;return this.bonusCountdown<=0;}if(this.fakePrecursorG>0){this.fakePrecursorG--;return false;}return false;}
 announceBonus(){if(!this.bonusPending)return false;this.bonusPayout=this.bonusType==='BIG'?BIG_PAYMENT:REG_PAYMENT;this.bonusRemaining=this.bonusPayout;this.bonusPending=false;this.state=this.bonusType==='BIG'?GAME_STATE.BONUS_BIG:GAME_STATE.BONUS_REG;if(this.bonusType==='BIG')storage.addBig();else storage.addReg();return true;}
 startBonusSpin(){if((this.state!==GAME_STATE.BONUS_BIG&&this.state!==GAME_STATE.BONUS_REG)||this.spinInProgress||this.bonusRemaining<=0)return false;this.currentRole={name:'押し順ベル',payment:Math.min(BONUS_BELL_PAYMENT,this.bonusRemaining),color:'yellow'};this.hintRole=this.currentRole;this.spinInProgress=true;this.payment=0;return true;}
 finishBonusSpin(){if(!this.spinInProgress)return false;const p=this.currentRole.payment;this.spinInProgress=false;this.credit+=p;storage.addPayout(p);this.bonusRemaining-=p;this.bonusGameG++;if(this.bonusRemaining<=0){this.state=GAME_STATE.CHALLENGE;this.challengeG=CHALLENGE_G;storage.addChallenge();return'CHALLENGE';}return'BONUS';}
 startChallengeSpin(){if(this.state!==GAME_STATE.CHALLENGE||this.spinInProgress||this.challengeG<=0)return false;this.challengeSmall=Math.random()<CHALLENGE_SMALL_ROLE_PROB;let role;if(this.challengeSmall){let r=Math.random(),c=0;for(const[k,v]of Object.entries(CHALLENGE_ROLE_RATES)){c+=v;if(r<c){role=NORMAL_ROLES[k];break;}}role=role||NORMAL_ROLES.BELL_3;}else role=Math.random()<.5?NORMAL_ROLES.REPLAY:NORMAL_ROLES.LOSE;this.currentRole=role;this.hintRole=role;this.payment=0;this.spinInProgress=true;return true;}
 finishChallengeSpin(){if(!this.spinInProgress)return false;this.spinInProgress=false;if(this.challengeSmall&&Math.random()<CHALLENGE_SUCCESS_RATE){this.challengeSuccess=true;this.challengeG=0;storage.addChallengeWin();this.startArt();return'ART';}this.challengeG--;if(this.challengeG<=0){this.state=GAME_STATE.NORMAL;this.challengeG=0;this.bonusType=null;this.bet=0;return'NORMAL';}return'CHALLENGE';}
 startArt(){this.state=GAME_STATE.ART;this.artG=ART_INITIAL_G;storage.addArt(ART_INITIAL_G);}
 addCredit(a){if(!Number.isFinite(a)||a<=0)return false;this.credit+=a;storage.addCredit(a);return true;}
 reset(){this.state=GAME_STATE.NORMAL;this.bet=0;this.currentRole=null;this.hintRole=null;this.payment=0;this.spinInProgress=false;this.bonusPending=false;this.bonusCountdown=0;this.bonusType=null;this.bonusRemaining=0;this.fakePrecursorG=0;this.challengeG=0;this.challengeSmall=false;this.challengeSuccess=false;this.artG=0;}
}
const game=new SlotGameV3();
