class GameControllerV3 {
 constructor(){this.isSpinning=false;this.stoppedReels=new Set();this.initializeElements();this.attach();this.load();this.idle();}
 initializeElements(){this.elements={maxBetBtn:document.getElementById('maxBetBtn'),addCreditBtn:document.getElementById('addCreditBtn'),startBtn:document.getElementById('startBtn'),stop1Btn:document.getElementById('stop1Btn'),stop2Btn:document.getElementById('stop2Btn'),stop3Btn:document.getElementById('stop3Btn'),resetBtn:document.getElementById('resetBtn'),settingSelect:document.getElementById('settingSelect')};}
 attach(){this.elements.maxBetBtn.onclick=()=>this.bet();this.elements.addCreditBtn.onclick=()=>{if(!this.isSpinning&&game.state===GAME_STATE.NORMAL&&game.addCredit(1000))renderer.update();};this.elements.startBtn.onclick=()=>this.start();this.elements.stop1Btn.onclick=()=>this.stop(1);this.elements.stop2Btn.onclick=()=>this.stop(2);this.elements.stop3Btn.onclick=()=>this.stop(3);this.elements.resetBtn.onclick=()=>this.reset();this.elements.settingSelect.onchange=e=>{game.setSetting(+e.target.value);renderer.update();};}
 load(){const s=storage.getStats();game.setting=s.setting;game.credit=s.credit;this.elements.settingSelect.value=s.setting;renderer.update();}
 idle(){const normal=game.state===GAME_STATE.NORMAL,bet=game.bet>0;this.elements.maxBetBtn.disabled=!normal||bet||this.isSpinning;this.elements.startBtn.disabled=this.isSpinning||(!bet&&normal)||game.state===GAME_STATE.ART;this.elements.stop1Btn.disabled=true;this.elements.stop2Btn.disabled=true;this.elements.stop3Btn.disabled=true;}
 bet(){if(this.isSpinning||game.state!==GAME_STATE.NORMAL||game.bet>0)return;if(!game.placeBet()){alert('クレジット不足です');return;}renderer.setEffectText('レバーを叩いてください。');renderer.update();this.idle();this.elements.startBtn.disabled=false;}
 start(){if(this.isSpinning)return;let ok=false;if(game.state===GAME_STATE.NORMAL)ok=game.rollNormal();else if(game.state===GAME_STATE.BONUS_BIG||game.state===GAME_STATE.BONUS_REG)ok=game.startBonusSpin();else if(game.state===GAME_STATE.CHALLENGE)ok=game.startChallengeSpin();if(!ok)return;this.isSpinning=true;this.stoppedReels.clear();this.elements.startBtn.disabled=true;this.elements.maxBetBtn.disabled=true;this.elements.stop1Btn.disabled=false;this.elements.stop2Btn.disabled=true;this.elements.stop3Btn.disabled=true;renderer.clearResult();renderer.startReels();renderer.startSpinEffect();renderer.update();}
 stop(n){if(!this.isSpinning||this.stoppedReels.has(n))return;if(n!==1&&!this.stoppedReels.has(1))return;this.stoppedReels.add(n);renderer.stopReel(n);renderer.onReelStopped(n);this.buttons();if(this.stoppedReels.size===3)setTimeout(()=>this.endSpin(),260);}
 buttons(){const first=this.stoppedReels.has(1);this.elements.stop1Btn.disabled=!this.isSpinning||first;this.elements.stop2Btn.disabled=!this.isSpinning||!first||this.stoppedReels.has(2);this.elements.stop3Btn.disabled=!this.isSpinning||!first||this.stoppedReels.has(3);}
 endSpin(){if(!this.isSpinning)return;this.isSpinning=false;renderer.stopAllReels();const state=game.state;
  if(state===GAME_STATE.NORMAL){const payout=game.currentRole?.payment||0;game.credit+=payout;storage.addGame(game.bet,payout);game.bet=0;const announce=game.advancePresentation();if(announce){game.announceBonus();renderer.showBonus(game.bonusType);this.idle();renderer.update();return;}renderer.showNormalResult();this.idle();renderer.update();return;}
  if(state===GAME_STATE.BONUS_BIG||state===GAME_STATE.BONUS_REG){const result=game.finishBonusSpin();if(result==='CHALLENGE')renderer.showChallenge(game.bonusType==='BIG');this.idle();renderer.update();return;}
  if(state===GAME_STATE.CHALLENGE){const result=game.finishChallengeSpin();if(result==='ART')renderer.setEffectText('――ART、突入。','bonus');else if(result==='NORMAL')renderer.setEffectText('5G、終了。通常時へ戻る。','normal');else renderer.setEffectText(`残り${game.challengeG}G。まだ終わらない。`,'chance');this.idle();renderer.update();return;}
  this.idle();renderer.update();}
 reset(){if(!confirm('データをリセットしますか？'))return;storage.resetData();game.credit=0;game.reset();this.isSpinning=false;this.stoppedReels.clear();this.elements.settingSelect.value=game.setting;this.idle();renderer.update();}
}
document.addEventListener('DOMContentLoaded',()=>{window.gameController=new GameControllerV3();});
