class RendererV3 {
 constructor(){this.e={gameState:document.getElementById('gameState'),currentG:document.getElementById('currentG'),r1:document.getElementById('reelStrip1'),r2:document.getElementById('reelStrip2'),r3:document.getElementById('reelStrip3'),hint:document.getElementById('hintBox'),role:document.getElementById('resultRole'),pay:document.getElementById('resultPayment'),bet:document.getElementById('betDisplay'),credit:document.getElementById('credit'),text:document.getElementById('演出テキスト'),totalGames:document.getElementById('totalGames'),totalBet:document.getElementById('totalBet'),totalPayout:document.getElementById('totalPayout'),percentage:document.getElementById('percentage'),big:document.getElementById('bigCount'),reg:document.getElementById('regCount'),art:document.getElementById('artCount'),artG:document.getElementById('artTotalG'),avg:document.getElementById('avgArtG'),sanku:document.getElementById('sankuCount'),burst:document.getElementById('burstCount'),setting:document.getElementById('settingDisplay')};this.w=[1,2,3].map(i=>this.e['r'+i].parentElement);this.t=[null,null,null];this.normal=['静かな時間が流れている。','いつもと変わらない一日だ。','何も変わらない。そう思った。','店内に、いつもの音が響く。','ふと、時計を見る。','小さな物音がした。','蒼生は気にせず前を向いた。','ただ時間だけが進んでいく。'];this.chance=['……今、何か見えなかったか。','ほんの少しだけ空気が変わった。','視界の端に妙な違和感。','何かが起こる気配がする。','まだ、はっきりとは分からない。','偶然にしては少し気になる。'];this.strong=['何かがおかしい。','さっきと同じ気配がした。','これは見過ごせない。','空気が変わった。','ここまで続くなら偶然ではない。','――何か来る。'];}
 pick(a){return a[Math.floor(Math.random()*a.length)];}
 setEffectText(s,k='normal'){const x=this.e.text;x.classList.remove('flash','effect-normal','effect-chance','effect-strong','effect-bonus');void x.offsetWidth;x.textContent=s;x.classList.add('flash','effect-'+k);}
 clearResult(){this.e.role.textContent='---';this.e.pay.textContent='0枚';}
 showNormalResult(){this.updateResult();}
 symbols(){return['7','BAR','ベル','リプ','スイカ','チェリー'];}
 target(role,i){const n=role?.name||'';if(n.includes('BIG'))return'7';if(n.includes('REG'))return'BAR';if(n.includes('押し順ベル')||n.includes('ベル'))return'ベル';if(n.includes('リプレイ'))return'リプ';if(n.includes('スイカ'))return'スイカ';if(n.includes('チェリー'))return'チェリー';if(n.includes('チャンス'))return i===2?'7':'BAR';return i===2?'7':'BAR';}
 setSymbol(i,s){const x=this.e['r'+i];x.innerHTML=`<div class="reel-symbol">${s}</div><div class="reel-symbol">${s}</div><div class="reel-symbol">${s}</div>`;x.style.transform='translateY(-70px)';}
 startReels(){this.w.forEach((w,i)=>{w.classList.remove('stopped','stopping');w.classList.add('spinning');clearInterval(this.t[i]);this.t[i]=setInterval(()=>{const x=this.e['r'+(i+1)],a=this.symbols();const q=()=>a[Math.floor(Math.random()*a.length)];x.innerHTML=`<div class="reel-symbol">${q()}</div><div class="reel-symbol">${q()}</div><div class="reel-symbol">${q()}</div>`;},65);});}
 stopReel(i){clearInterval(this.t[i-1]);this.t[i-1]=null;const w=this.w[i-1];w.classList.remove('spinning');w.classList.add('stopping');this.setSymbol(i,this.target(game.currentRole,i));w.classList.add('stopped');}
 stopAllReels(){this.t.forEach((x,i)=>{clearInterval(x);this.t[i]=null;this.w[i].classList.remove('spinning');});}
 kind(){if(game.bonusPending)return game.bonusCountdown<=1?'strong':'chance';if(game.fakePrecursorG>0)return game.fakePrecursorG===1?'strong':'chance';const n=game.currentRole?.name||'';if(n.includes('強チェリー')||n.includes('チャンス目'))return'maybe';if(n.includes('スイカ')||n.includes('弱チェリー'))return Math.random()<.35?'chance':'normal';return'normal';}
 startSpinEffect(){const k=this.kind();const a=k==='strong'?this.strong:k==='chance'||k==='maybe'?this.chance:this.normal;this.setEffectText(this.pick(a),k==='maybe'?'chance':k);}
 onReelStopped(i){const k=this.kind();let s;if(game.bonusPending&&game.bonusCountdown<=1&&i===3)s='――その先に、何かがある。';else if(game.fakePrecursorG>0&&i===3)s='――まだ終わっていない。';else if(k==='strong')s=i===1?'確かに、今のは違った。':i===2?'まだ気配が消えない。':'――何か来る。';else if(k==='chance')s=i===1?'……何かいる？':i===2?'もう一度、同じ気配がした。':'――気のせいではないのかもしれない。';else s=i===1?'蒼生は、ふと視線を上げた。':i===2?'何かの気配がした。':'――何事もなく、時が流れた。';this.setEffectText(s,k);}
 showBonus(type){this.setEffectText(type==='BIG'?'――BONUS―― BIG 250枚':'――BONUS―― REG 70枚','bonus');this.e.role.textContent=type;this.e.pay.textContent=type==='BIG'?'残り250枚':'残り70枚';}
 showChallenge(){this.setEffectText('5GのART CHALLENGE。自分で回して引き当てろ。','chance');this.e.role.textContent='ART CHALLENGE';this.e.pay.textContent=`残り${game.challengeG}G`;}
 updateState(){const m={NORMAL:['通常時','state-normal'],BONUS_BIG:['BIG','state-bonus'],BONUS_REG:['REG','state-bonus'],CHALLENGE:['ART CHALLENGE','state-art'],ART:['ART','state-art']};const x=m[game.state]||['通常時','state-normal'];this.e.gameState.textContent=x[0];this.e.gameState.className='state-badge '+x[1];let g=game.state===GAME_STATE.CHALLENGE?game.challengeG:game.state===GAME_STATE.BONUS_BIG||game.state===GAME_STATE.BONUS_REG?Math.ceil(game.bonusRemaining/Math.max(1,BONUS_BELL_PAYMENT)):game.artG;this.e.currentG.textContent=g>0?`残り: ${g}G`:'残り: --G';}
 updateHint(){this.e.hint.className='hint-box';if(game.currentRole){this.e.hint.classList.add('hint-'+(game.currentRole.color||'white'),'active');if(game.bonusPending)this.e.hint.textContent=game.bonusCountdown<=1?'本前兆・最終局面':'前兆継続';else if(game.fakePrecursorG>0)this.e.hint.textContent='前兆示唆';else if(game.state===GAME_STATE.CHALLENGE)this.e.hint.textContent=game.challengeSmall?'小役成立':'通常';else this.e.hint.textContent='予告';}}
 updateResult(){if(game.spinInProgress)return;if(game.state===GAME_STATE.BONUS_BIG||game.state===GAME_STATE.BONUS_REG){this.e.role.textContent=game.bonusType;this.e.pay.textContent=`残り${game.bonusRemaining}枚`;return;}if(game.state===GAME_STATE.CHALLENGE){this.e.role.textContent='ART CHALLENGE';this.e.pay.textContent=`残り${game.challengeG}G`;return;}if(game.currentRole){this.e.role.textContent=game.currentRole.name;this.e.pay.textContent=`${game.payment||0}枚`;}}
 update(){this.updateState();this.updateHint();this.updateResult();this.e.bet.textContent=`${game.bet}枚`;this.e.credit.textContent=game.credit;const s=storage.getStats();this.e.totalGames.textContent=s.totalGames;this.e.totalBet.textContent=s.totalBet;this.e.totalPayout.textContent=s.totalPayout;this.e.percentage.textContent=s.percentage+'%';this.e.big.textContent=s.bigCount;this.e.reg.textContent=s.regCount;this.e.art.textContent=s.artCount;this.e.artG.textContent=s.artTotalG;this.e.avg.textContent=s.avgArt+'G';this.e.sanku.textContent=s.sankuCount;this.e.burst.textContent=s.burstCount;this.e.setting.textContent=s.setting;}
}
const renderer=new RendererV3();
